version: "3.8"
services:
  neo4j:
    image: neo4j:5.19-community
    container_name: neo4j
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/testmaster123
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"   # Neo4j Browser (HTTP)
      - "7687:7687"   # Bolt (Treiber)
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
