CREATE CONSTRAINT ent_name IF NOT EXISTS FOR (n:Entity)   REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT doc_id   IF NOT EXISTS FOR (n:Document) REQUIRE n.id   IS UNIQUE;
CREATE FULLTEXT INDEX doc_text_fts IF NOT EXISTS FOR (d:Document) ON EACH [d.text];
