prodct_names =
[
  "GIGA R1 WiFi",
  "Braccio Carrier",
  "Mega 2560 Rev3",
  "Plug and Make Kit",
  "Due",
  "GIGA Display Shield",
  "DIN Celsius",
  "DIN Simul8",
  "Make Your UNO Kit",
  "Alvik",
  "Cloud Editor",
  "Node Red",
  "MKR IoT Carrier",
  "MKR WAN 1310",
  "MKR IoT Carrier Rev2",
  "MKR WiFi 1010",
  "MKR Vidor 4000",
  "Modulino Buzzer",
  "Modulino Thermo",
  "Modulino Movement",
  "Modulino Knob",
  "Nicla Sense ME",
  "Modulino Distance",
  "Modulino Pixels",
  "Nicla Vision",
  "Modulino Buttons",
  "Nicla Voice",
  "Nicla Sense Env",
  "Opta",
  "Opta Analog Expansion A0602",
  "Portenta Machine Control",
  "Opta Digital Expansion D1608E - D1608S",
  "WisGate Edge Pro",
  "Edge Control",
  "Stella",
  "Portenta Proto Kit VE",
  "Portenta Proto Kit ME",
  "WisGate Edge Lite 2",
  "Nano 33 IoT",
  "Nano 33 BLE",
  "Nano Every",
  "Nano RP2040 Connect",
  "Nano ESP32",
  "Nano Connector Carrier",
  "Nano 33 BLE Sense",
  "Nano 33 BLE Rev2",
  "Nano 33 BLE Sense Rev2",
  "Nano",
  "Nano Screw Terminal Adapter",
  "Nano Matter",
  "Nano R4"
]
category_names =
[
  "Mega",
  "Education",
  "Kits",
  "Arduino Cloud",
  "MKR Family",
  "Modulino Family",
  "Nicla Family",
  "Opta Family",
  "Pro Solutions Kits",
  "Nano Family"
]

