import typing as t
import pandas as pd

from copilot_rag.tools.llm_judge.common import (
    validate_response,
    TestCase,
    is_apology_response,
)
from copilot_rag.tools.llm_judge.common import EvaluationResult
from copilot_rag.tools.llm_judge.metrics.metric import Metric
from copilot_rag.databricks import DatabricksServicePrincipal


JUDGE_ANSWER_CORRECTNESS_PROMPT = """
You are evaluating whether a support bot correctly responded to user questions.

You will be provided:

**A question**:
{question}

**Expected_causes**:
{expected_causes}

Each cause has its own list of **instructions**:
{expected_steps}

An **actual answer** generated by the bot:
{actual_answer}

You will judge the actual answer against the expected causes and instructions by following these steps:
Question Type Determination:
- If expected_causes are provided: This is a "service request" (troubleshooting) question
- If no expected_causes are provided: This is a "procedure description" question

Your Task:

1. Determine if the bot gave:
   - An **answer** to the user question,
   - Or a **missing answer** (a meta-response) that does not address the user question
     Examples of missing answers/meta-responses include: refusals or inability to answer,
     searching/no-info statements, or asking for more details, such as:
     "I'm sorry I cannot answer...", "I have searched all the available documents for...",
     "I couldn't find relevant information", "No information available", "Please provide more details".

2. For missing answers/meta-responses (as above), evaluate them as *false negatives* (FN).

3. For service requests (when expected causes are provided):
   - Evaluate both causes and steps
   - Evaluate whether the causes match expected ones (semantically)
   - Evaluate whether the steps are factually correct and mostly complete
   - Allow for differences (wording, order, safety additions)
   - Classify as:
     * TP: {tp_definition}
     * FP: {fp_definition}
     * FN: A missing response or meta-response that declines to answer or asks for more info

4. For procedure descriptions (when no expected causes are provided):
   - Focus on the sequence and completeness of steps
   - Allow for equivalent but differently worded instructions
   - Consider steps that cover the same action in different ways as matches
   - Classify as:
     * TP: {tp_definition}
     * FP: {fp_definition}
     * FN: A missing response or meta-response that declines to answer or asks for more info

5. For both types:
   - Allow differences in wording
   - Penalize missing critical steps
   - Consider semantic equivalence

Respond in valid JSON using this format:
{{
  "category": "<TP | FP | TN | FN>",
  "justification": "<Explain whether the causes and steps matched,
  and why the classification is correct. Mention any inaccuracies or gaps.>"
}}
"""  # noqa


class Correctness(Metric):
    """Evaluate procedure description responses."""

    def __init__(
            self,
            openai_spn: DatabricksServicePrincipal,
            openai_baseurl: str,
            openai_model_name: str,
            openai_embeddings_name: str,
            openai_temperature: float,
            relaxed: bool = False
    ):
        """Initialize a correctness judge.

        Args:
            openai_spn: Databricks service principal for authentication
            openai_baseurl: Base URL for OpenAI API
            openai_model_name: Name of the model to use for judging
            openai_embeddings_name: Name of the embeddings model
            relaxed: Whether to use relaxed TP/FP criteria
        """
        super().__init__(
            "correctness",
            openai_spn,
            openai_baseurl,
            openai_model_name,
            openai_embeddings_name,
            openai_temperature
        )
        self._relaxed = relaxed

    def evaluate(self, context: TestCase) -> t.Dict[str, float]:
        """Evaluate correctness/completeness of procedure descriptions."""
        if not context.expected_answers:
            raise ValueError("no expected answer specified")

        if context.answer and is_apology_response(context.answer):
            return {
                self.name: {
                    "category": "fn",
                    "justification": (
                        "The response is a meta-response (apology/no-information/"  # noqa: E501
                        "request for more details) and does not answer the user question; "  # noqa: E501
                        "therefore it is classified as FN."
                    )
                }
            }

        expected_causes = "No causes are expected."
        if len(context.expected_answers) > 1 and context.expected_answers[1]:
            expected_causes = context.expected_answers[1]

        tp_definition = (
            "The given information is related to the user's question, and it "
            "contains at least one step/cause/information given in the "
            "expected answer"
            if self._relaxed
            else "ALL expected steps/causes are present in the response even "
            "if worded differently"
        )
        fp_definition = (
            "A response was provided and it attempts to answer but is not related "  # noqa: E501
            "to the user question. Do NOT classify meta-responses (apologies, no-"  # noqa: E501
            "information, 'searched' statements, or requests for more details) as FP; "  # noqa: E501
            "those are FN."
            if self._relaxed
            else "A response was provided but at least one expected step/cause is "  # noqa: E501
            "missing or the response isn't aligned with the expected troubleshooting "  # noqa: E501
            "instructions. Do NOT classify meta-responses (apologies, no-information, "  # noqa: E501
            "'searched' statements, or requests for more details) as FP; those are FN."  # noqa: E501
        )

        response = self._judge(
            JUDGE_ANSWER_CORRECTNESS_PROMPT.format(
                question=context.question,
                actual_answer=context.answer,
                expected_steps=context.expected_answers[0],
                expected_causes=expected_causes,
                tp_definition=tp_definition,
                fp_definition=fp_definition,
            )
        )
        return {
            self.name: validate_response(
                response,
                fields=[
                    ("category", str),
                    ("justification", str)
                ])
        }

    def aggregate(self, results: t.List[EvaluationResult]) -> t.Dict:
        """Compute accuracy over a set of results."""
        # Filter only the results which contain a correctness evaluation.

        results = filter(lambda x: self.name in x.metrics, results)
        classes = pd.Series(
            res.metrics[self.name]["category"].lower()
            for res in results
        )

        counts = classes.value_counts()

        tp = counts.get("tp", 0)
        fp = counts.get("fp", 0)
        tn = counts.get("tn", 0)
        fn = counts.get("fn", 0)

        accuracy = (tp + tn) / (tp + tn + fp + fn)
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0

        return {
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall
        }
